# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a619a11eb137bbfbafaaca143519222b6671c5547c0d11e221bd1e202c250d83649098eb389e377ca834de1a9c996851f4f0ddd652a6f64161f604a7e25bf3b2

test:
  secret_key_base: 5cedb7ebacba35de038125a76aadb0c3571b94421267b87927013ead1a0cb76311ade15e1f09003e26ae473690e4a2aa31d76f774c23b83671223571c3510f8c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
